export const MODULES = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    description: 'Overview of the Aerodyne Fleet OS platform, navigation, and core concepts.',
    icon: '🚀',
    color: '#f59e0b',
    level: 'Beginner',
    questions: [
      {
        question: 'What is the primary purpose of the Aerodyne Fleet OS?',
        options: [
          'Managing airline ticket bookings and passenger reservations',
          'A digital aviation operations and maintenance management platform',
          'A weather forecasting system for pilots',
          'A fuel purchasing and contract management system only',
        ],
        answer: 1,
        explanation: 'Aerodyne Fleet OS is a comprehensive digital platform for aviation operations including fleet management, maintenance, dispatch, crew operations, and more.',
      },
      {
        question: 'How do you navigate between different modules in the platform?',
        options: [
          'By typing commands in a terminal window',
          'Using the left navigation rail or mobile bottom tab bar',
          'By reloading the page and selecting a new module',
          'Through email links sent by the system',
        ],
        answer: 1,
        explanation: 'The platform uses a left navigation rail on desktop and a bottom tab bar on mobile, providing organized access to all modules.',
      },
      {
        question: 'What does the screensaver display when the system is idle?',
        options: [
          'A blank black screen to save energy',
          'Random stock photos from the internet',
          'Module showcases with live fleet stats, a Zulu clock, and operational data',
          'The login screen prompting re-authentication',
        ],
        answer: 2,
        explanation: 'The screensaver cycles through platform modules with live fleet data, a Zulu time clock, and operational stats drawn from the live database.',
      },
      {
        question: 'What is "Zulu time" as displayed in the system?',
        options: [
          'Local time at the headquarters airport',
          'UTC (Coordinated Universal Time) used as the global aviation standard',
          'The time zone of the aircraft\'s destination',
          'Eastern Standard Time used by the operations team',
        ],
        answer: 1,
        explanation: 'Zulu time refers to UTC — the universal time standard used across aviation to avoid confusion between time zones.',
      },
      {
        question: 'Which role has the highest level of access in the platform?',
        options: ['Technician', 'Dispatcher', 'Admin', 'Flight Attendant'],
        answer: 2,
        explanation: 'Admin users have full access to all modules, user management, and system configuration settings.',
      },
    ],
  },
  {
    id: 'fleet-management',
    title: 'Fleet Management',
    description: 'Learn how to track aircraft status, capabilities, and fleet health.',
    icon: '✈️',
    color: '#06b6d4',
    level: 'Beginner',
    questions: [
      {
        question: 'What does "OOS" stand for in the Fleet Dashboard?',
        options: ['Out of Schedule', 'Out of Service', 'On Operating Status', 'Overhaul On Site'],
        answer: 1,
        explanation: 'OOS means Out of Service — the aircraft is grounded and not available for revenue flight until maintenance is completed.',
      },
      {
        question: 'What is a "tail number" in the context of the fleet registry?',
        options: [
          'The maintenance log page number for the aircraft',
          'The flight number assigned by the airline',
          'The unique registration identifier for an individual aircraft (e.g. N455GJ)',
          'The aircraft\'s gate assignment code',
        ],
        answer: 2,
        explanation: 'A tail number (also called registration) uniquely identifies a specific aircraft — like a license plate for airplanes.',
      },
      {
        question: 'What does the "MCC Watch" flag on an aircraft mean?',
        options: [
          'The aircraft has been recently washed and inspected',
          'MCC has flagged the aircraft for heightened attention by all personnel',
          'The aircraft is scheduled for a marketing photo shoot',
          'The aircraft\'s maintenance contract has been renewed',
        ],
        answer: 1,
        explanation: 'The MCC Watch flag indicates that Maintenance Control Center has escalated concern about this aircraft and all personnel should be aware.',
      },
      {
        question: 'What is ETOPS authorization?',
        options: [
          'Clearance for pilots to fly overtime hours',
          'Permission to carry extra cargo on wide-body aircraft',
          'Extended Twin Operations — allows twin-engine aircraft to fly routes far from diversion airports',
          'Approval for electronic tablet use in the cockpit',
        ],
        answer: 2,
        explanation: 'ETOPS (Extended-range Twin-engine Operational Performance Standards) authorizes twin-engine aircraft to fly routes more than 60 minutes from an emergency diversion airport.',
      },
      {
        question: 'What does "CAT IIIb" approval mean for an aircraft?',
        options: [
          'The aircraft is certified to carry Category B cargo',
          'The aircraft can land using ILS in very low visibility conditions (RVR as low as 75m)',
          'The aircraft has passed Category 3 safety inspection',
          'The aircraft is approved for transoceanic flights',
        ],
        answer: 1,
        explanation: 'CAT IIIb refers to an ILS instrument landing approach category allowing operations in very low visibility, with RVR (Runway Visual Range) as low as 75 meters.',
      },
    ],
  },
  {
    id: 'maintenance-control',
    title: 'Maintenance Control (MCC)',
    description: 'Understand MCC operations, AOG recovery, and Positive Fix Locks.',
    icon: '🔧',
    color: '#ef4444',
    level: 'Intermediate',
    questions: [
      {
        question: 'What is a "Positive Fix Lock" in the MCC module?',
        options: [
          'A physical lock placed on the aircraft nose wheel',
          'A software lock placed by MCC requiring technician concurrence before return to service',
          'An administrative lock preventing flight crew from changing routes',
          'A fuel cap locking mechanism',
        ],
        answer: 1,
        explanation: 'A Positive Fix Lock is placed by MCC when an aircraft requires a confirmed fix with technician concurrence before it can be returned to service.',
      },
      {
        question: 'What does "AOG" stand for?',
        options: ['Aircraft On Ground', 'Approved Operations Guide', 'Active Outbound Gate', 'Aircraft Operations Group'],
        answer: 0,
        explanation: 'AOG means Aircraft On Ground — the aircraft is grounded due to a critical maintenance issue and cannot fly until resolved.',
      },
      {
        question: 'What is the purpose of a "Field Trip" in the MCC module?',
        options: [
          'Sending crew members on a sightseeing tour',
          'Managing recovery operations at remote stations with technician tracking and logistics',
          'Scheduling pilots for route familiarization flights',
          'Sending maintenance manuals to outstations',
        ],
        answer: 1,
        explanation: 'Field Trips track recovery operations at remote stations including assigned technicians, hotel accommodations, expenses, and flight details.',
      },
      {
        question: 'What must happen before a technician concurrence removes a Positive Fix Lock?',
        options: [
          'The captain must sign off the logbook',
          'A 24-hour cooling-off period must elapse',
          'The technician must provide their name, certificate number, and concurrence notes',
          'The airline dispatch must approve the removal via email',
        ],
        answer: 2,
        explanation: 'Technician concurrence requires the technician\'s name, certificate/employee number, and notes confirming the fix — creating a traceable record.',
      },
      {
        question: 'Which module would you use to monitor oil consumption trends across the fleet?',
        options: ['Fleet Registry', 'Engine Health Analytics', 'Crew Control', 'Dispatch Workstation'],
        answer: 1,
        explanation: 'Engine Health Analytics tracks EGT margin trends, oil consumption rates, and LLP (Life-Limited Parts) cycles, escalating alerts to Engineering and MCC.',
      },
    ],
  },
  {
    id: 'techops-logbook',
    title: 'TechOps Electronic Logbook',
    description: 'Learn how to create discrepancies, corrective actions, and digital signatures.',
    icon: '📋',
    color: '#8b5cf6',
    level: 'Intermediate',
    questions: [
      {
        question: 'What is the primary purpose of the TechOps Electronic Logbook?',
        options: [
          'Scheduling crew rest periods',
          'Recording aircraft discrepancies, corrective actions, and digital sign-offs per 14 CFR Part 43',
          'Filing flight plans with ATC',
          'Tracking gate assignments at airports',
        ],
        answer: 1,
        explanation: 'The TechOps Logbook is a fully digital aircraft logbook compliant with 14 CFR Part 43, recording maintenance discrepancies, corrective actions, and legally traceable digital signatures.',
      },
      {
        question: 'What does "RII" stand for in maintenance operations?',
        options: [
          'Required Inspection Item — a critical repair that must be independently inspected',
          'Routine Inspection Interval for scheduled maintenance',
          'Remote Inspection Integration system',
          'Return to Inventory Item for surplus parts',
        ],
        answer: 0,
        explanation: 'RII (Required Inspection Item) designates repairs so critical to flight safety that they must be inspected by a separate qualified individual, not the performing technician.',
      },
      {
        question: 'What hashing algorithm is used to sign logbook entries digitally?',
        options: ['MD5', 'SHA-1', 'SHA-256', 'AES-128'],
        answer: 2,
        explanation: 'SHA-256 cryptographic hashing is used to create a tamper-evident signature for each logbook entry, ensuring its integrity over time.',
      },
      {
        question: 'What is a "MEL deferral" in the logbook context?',
        options: [
          'Delaying a flight by more than 15 minutes',
          'Deferring a discrepancy to a later date using the Minimum Equipment List authorization',
          'Postponing an engine overhaul to save costs',
          'Pushing back a scheduled crew rest period',
        ],
        answer: 1,
        explanation: 'A MEL (Minimum Equipment List) deferral allows an aircraft to continue operating with a specific inoperative item under defined conditions, documented in the logbook.',
      },
      {
        question: 'What happens when a logbook entry is marked "signed"?',
        options: [
          'It is deleted from the system after 30 days',
          'It is locked from further modification and the signature hash is recorded',
          'It is emailed to the airline\'s quality department automatically',
          'It is converted to a PDF and archived on an external server',
        ],
        answer: 1,
        explanation: 'Once signed, a logbook entry is locked from modification. The content hash at signing time is stored, so any tampering can be detected.',
      },
    ],
  },
  {
    id: 'dispatch',
    title: 'Dispatch Workstation',
    description: 'Master flight releases, ETOPS validation, and regulatory compliance tools.',
    icon: '📡',
    color: '#06b6d4',
    level: 'Advanced',
    questions: [
      {
        question: 'What is an "Electronic Flight Release"?',
        options: [
          'A digital boarding pass sent to passengers',
          'The official authorization document issued by a dispatcher releasing a flight for operation',
          'An email confirming the aircraft has been cleaned',
          'A software update pushed to the aircraft\'s FMS',
        ],
        answer: 1,
        explanation: 'An Electronic Flight Release is the official regulatory document that a licensed dispatcher issues to authorize a specific flight, verifying fuel, weather, crew legality, and aircraft airworthiness.',
      },
      {
        question: 'Under FAR 117, what is "Flight Duty Period" (FDP)?',
        options: [
          'The total time the aircraft is airborne',
          'The period from when a crew member reports for duty until the aircraft is parked after the last flight',
          'The time spent on ground between two consecutive flights',
          'The period a pilot is required to rest before a flight',
        ],
        answer: 1,
        explanation: 'FDP (Flight Duty Period) under FAR 117 is measured from when a crew member reports to duty until the aircraft engines are shut down after the last segment — used to enforce fatigue limits.',
      },
      {
        question: 'What does the Dispatch Workstation check for ETOPS validation?',
        options: [
          'Whether the aircraft has a valid paint scheme',
          'Per-tail ETOPS authorization vs. engine health, oil consumption, and MEL deferrals',
          'Whether the crew has eaten a meal before the flight',
          'If the aircraft has been washed within the last 30 days',
        ],
        answer: 1,
        explanation: 'ETOPS validation cross-references the aircraft\'s tail-level authorization against current engine health data, oil consumption trends, and any MEL deferrals that might downgrade the ETOPS rating.',
      },
      {
        question: 'What does "CAT approach authorization" allow a dispatcher to verify?',
        options: [
          'Whether the aircraft is authorized for Category C cargo',
          'Whether the aircraft and airport are certified for low-visibility precision instrument approaches',
          'The airline\'s category on the IATA safety audit',
          'Whether the cat (animal) policy is active on the aircraft',
        ],
        answer: 1,
        explanation: 'CAT (Category) approval for ILS approaches ensures both the aircraft and destination airport are certified for low-visibility operations such as CAT II or CAT III landings.',
      },
      {
        question: 'What is the purpose of the "AI Dispatch Copilot" module?',
        options: [
          'To replace licensed dispatchers with artificial intelligence',
          'To provide AI-assisted situational awareness, delay predictions, and recovery recommendations',
          'To automatically file flight plans with the FAA',
          'To generate passenger seat assignments using AI',
        ],
        answer: 1,
        explanation: 'The AI Dispatch Copilot supplements human dispatchers with predictive delay analysis, weather insights, and IROPS recovery recommendations — it does not replace the licensed dispatcher.',
      },
    ],
  },
  {
    id: 'mel-airworthiness',
    title: 'MEL & Airworthiness',
    description: 'Understand MEL categories, deferrals, and fleet airworthiness management.',
    icon: '📝',
    color: '#3b82f6',
    level: 'Advanced',
    questions: [
      {
        question: 'What does MEL stand for?',
        options: ['Maximum Equipment List', 'Minimum Equipment List', 'Mandatory Engineering Limit', 'Mechanical Error Log'],
        answer: 1,
        explanation: 'MEL stands for Minimum Equipment List — the FAA-approved document that defines which systems and components an aircraft can be dispatched with inoperative.',
      },
      {
        question: 'What is a MEL Category "A" item?',
        options: [
          'An item that can be deferred for up to 30 days with no restrictions',
          'An item with no specific repair interval — it can remain deferred indefinitely',
          'The most critical category — must be repaired before the next flight or within a specified short interval',
          'An item that only applies to cargo aircraft',
        ],
        answer: 2,
        explanation: 'MEL Category A items are the most urgent — they must be repaired before the next flight or within a very short, specifically defined time interval.',
      },
      {
        question: 'What is the repair interval for a MEL Category "C" item?',
        options: ['Before next flight', 'Within 3 calendar days', 'Within 10 calendar days', 'Within 120 calendar days'],
        answer: 2,
        explanation: 'MEL Category C items must be repaired within 10 calendar days from the date of discovery/deferral.',
      },
      {
        question: 'What is a "Chronic MEL" item?',
        options: [
          'A recurring MEL item that has been deferred and re-deferred multiple times without permanent resolution',
          'A MEL item that only appears during chronic weather conditions',
          'A MEL item that costs more than $10,000 to repair',
          'Any MEL item that is older than 90 days',
        ],
        answer: 0,
        explanation: 'A Chronic MEL item is one that keeps recurring — repeatedly deferred and rediscovered — indicating a systemic issue that may require engineering intervention.',
      },
      {
        question: 'What is a "Certificate of Release to Service" (CRS)?',
        options: [
          'A document releasing a passenger from customs',
          'The legal certification by an authorized person that maintenance has been completed and the aircraft is airworthy',
          'A release form for contracted maintenance workers',
          'A document releasing the aircraft from its lease agreement',
        ],
        answer: 1,
        explanation: 'A CRS (or Return to Service per 14 CFR 43.9) is the required legal certification — signed by an authorized A&P mechanic or IA — confirming maintenance was performed per approved data and the aircraft is airworthy.',
      },
    ],
  },
];