import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import {
  FileText, Cloud, AlertTriangle, CheckCircle, Users,
  Wind, Fuel, Navigation2, Plane, Lock
} from 'lucide-react';
import { cn } from '@/lib/utils';

const TABS = [
  { key: 'route',      label: 'Route',      icon: Navigation2 },
  { key: 'fuel',       label: 'Fuel',       icon: Fuel },
  { key: 'weather',    label: 'Weather',    icon: Cloud },
  { key: 'performance',label: 'Performance',icon: Plane },
  { key: 'crew',       label: 'Crew',       icon: Users },
  { key: 'review',     label: 'Review',     icon: FileText },
];

function SectionTile({ icon: Icon, title, status, complete }) {
  return (
    <div className={cn(
      'rounded-xl border px-4 py-3 flex items-center justify-between',
      complete ? 'bg-green-500/10 border-green-500/30' : 'bg-orange-500/10 border-orange-500/30'
    )}>
      <div className="flex items-center gap-3">
        <Icon className={cn('w-4 h-4', complete ? 'text-green-400' : 'text-orange-400')} />
        <div>
          <p className="text-sm font-semibold text-foreground">{title}</p>
          <p className="text-xs text-muted-foreground">{status}</p>
        </div>
      </div>
      {complete && <CheckCircle className="w-4 h-4 text-green-400" />}
    </div>
  );
}

export default function DispatchReleaseBuilder({ flights = [], releases = [], crew = [] }) {
  const [selectedFlight, setSelectedFlight] = useState(flights[0]?.flight_number || null);
  const [activeTab, setActiveTab] = useState('route');
  const [formData, setFormData] = useState({
    route: '',
    cruise_altitude: 'FL350',
    cruise_speed: 'M.82',
    fuel_on_board: 0,
    min_fuel_required: 0,
    alternate: '',
    weather_approved: false,
    mel_approved: false,
    crew_approved: false,
    performance_approved: false,
  });

  const queryClient = useQueryClient();
  const flight = flights.find(f => f.flight_number === selectedFlight);
  const existingRelease = releases.find(r => r.flight_number === selectedFlight);

  const createMutation = useMutation({
    mutationFn: (data) => base44.entities.DispatchRelease.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['dispatch-releases'] });
      alert('Release created successfully');
    },
  });

  const handleSubmit = async () => {
    if (!flight) return;

    const releaseData = {
      flight_number: flight.flight_number,
      flight_date: flight.flight_date,
      aircraft_tail: flight.aircraft_tail,
      origin: flight.origin,
      destination: flight.destination,
      alternate: formData.alternate,
      route: formData.route,
      cruise_altitude: formData.cruise_altitude,
      cruise_speed: formData.cruise_speed,
      release_status: 'pending_signature',
      fuel_section: {
        fuel_on_board: formData.fuel_on_board,
        min_fuel_required: formData.min_fuel_required,
      },
      weather_section: {
        weather_approved: formData.weather_approved,
      },
      mel_cdl_section: {
        approved_for_dispatch: formData.mel_approved,
      },
      crew_section: {
        crew_legality_approved: formData.crew_approved,
      },
      remarks: 'Release generated by Dispatch Workstation',
    };

    createMutation.mutate(releaseData);
  };

  const completionStatus = {
    route: formData.route && formData.alternate,
    fuel: formData.fuel_on_board > 0 && formData.min_fuel_required > 0,
    weather: formData.weather_approved,
    performance: formData.performance_approved,
    crew: formData.crew_approved,
    mel: formData.mel_approved,
  };

  const allComplete = Object.values(completionStatus).every(v => v);

  return (
    <div className="space-y-4">
      {/* Flight selector */}
      <div>
        <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider block mb-2">
          Select Flight
        </label>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
          {flights.map(f => (
            <button
              key={f.id}
              onClick={() => { setSelectedFlight(f.flight_number); setActiveTab('route'); }}
              className={cn(
                'rounded-lg border px-4 py-2 text-left text-sm font-semibold transition-all focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1',
                selectedFlight === f.flight_number
                  ? 'bg-primary text-primary-foreground border-primary'
                  : 'border-border text-muted-foreground hover:text-foreground'
              )}
            >
              <p className="font-mono">{f.flight_number}</p>
              <p className="text-xs text-current opacity-70">{f.origin} → {f.destination}</p>
            </button>
          ))}
        </div>
      </div>

      {flight && (
        <>
          {/* Completion tiles */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
            <SectionTile icon={Navigation2} title="Route" status={completionStatus.route ? 'Complete' : 'Pending'} complete={completionStatus.route} />
            <SectionTile icon={Fuel} title="Fuel" status={completionStatus.fuel ? 'Complete' : 'Pending'} complete={completionStatus.fuel} />
            <SectionTile icon={Cloud} title="Weather" status={completionStatus.weather ? 'Approved' : 'Pending'} complete={completionStatus.weather} />
            <SectionTile icon={Plane} title="Performance" status={completionStatus.performance ? 'Approved' : 'Pending'} complete={completionStatus.performance} />
            <SectionTile icon={Users} title="Crew Legality" status={completionStatus.crew ? 'Approved' : 'Pending'} complete={completionStatus.crew} />
            <SectionTile icon={AlertTriangle} title="MEL/CDL" status={completionStatus.mel ? 'Approved' : 'Pending'} complete={completionStatus.mel} />
          </div>

          {/* Tabs */}
          <div className="flex gap-1 bg-secondary rounded-xl p-1 overflow-x-auto scrollbar-hide">
            {TABS.map(t => (
              <button
                key={t.key}
                onClick={() => setActiveTab(t.key)}
                className={cn(
                  'flex items-center gap-1.5 whitespace-nowrap text-xs font-semibold px-3 py-2 rounded-lg transition-all flex-shrink-0',
                  activeTab === t.key ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground'
                )}
              >
                <t.icon className="w-3.5 h-3.5" />
                {t.label}
              </button>
            ))}
          </div>

          {/* Tab content */}
          <div className="rounded-xl bg-card border border-border p-4 space-y-3">
            {activeTab === 'route' && (
              <div className="space-y-3">
                <div>
                  <label className="text-xs font-semibold text-muted-foreground block mb-1">Route</label>
                  <input
                    type="text"
                    placeholder="e.g. DEP STAR TRANSITION AIRWAY APPROACH"
                    value={formData.route}
                    onChange={e => setFormData({ ...formData, route: e.target.value })}
                    className="w-full h-10 bg-background border border-border rounded-lg px-3 text-sm font-mono text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                  />
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <label className="text-xs font-semibold text-muted-foreground block mb-1">Cruise Altitude</label>
                    <input
                      type="text"
                      value={formData.cruise_altitude}
                      onChange={e => setFormData({ ...formData, cruise_altitude: e.target.value })}
                      className="w-full h-10 bg-background border border-border rounded-lg px-3 text-sm font-mono text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-muted-foreground block mb-1">Cruise Speed</label>
                    <input
                      type="text"
                      value={formData.cruise_speed}
                      onChange={e => setFormData({ ...formData, cruise_speed: e.target.value })}
                      className="w-full h-10 bg-background border border-border rounded-lg px-3 text-sm font-mono text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                  </div>
                </div>
                <div>
                  <label className="text-xs font-semibold text-muted-foreground block mb-1">Alternate Airport</label>
                  <input
                    type="text"
                    placeholder="e.g. KORD"
                    value={formData.alternate}
                    onChange={e => setFormData({ ...formData, alternate: e.target.value })}
                    className="w-full h-10 bg-background border border-border rounded-lg px-3 text-sm font-mono text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                  />
                </div>
              </div>
            )}

            {activeTab === 'fuel' && (
              <div className="space-y-3">
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <label className="text-xs font-semibold text-muted-foreground block mb-1">Fuel On Board (lbs)</label>
                    <input
                      type="number"
                      value={formData.fuel_on_board}
                      onChange={e => setFormData({ ...formData, fuel_on_board: Number(e.target.value) })}
                      className="w-full h-10 bg-background border border-border rounded-lg px-3 text-sm font-mono text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-muted-foreground block mb-1">Min Required (lbs)</label>
                    <input
                      type="number"
                      value={formData.min_fuel_required}
                      onChange={e => setFormData({ ...formData, min_fuel_required: Number(e.target.value) })}
                      className="w-full h-10 bg-background border border-border rounded-lg px-3 text-sm font-mono text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                  </div>
                </div>
                {formData.fuel_on_board > 0 && formData.min_fuel_required > 0 && (
                  <div className="bg-green-500/10 border border-green-500/30 rounded-lg px-3 py-2">
                    <p className="text-xs font-semibold text-green-400">✓ Fuel margins adequate</p>
                  </div>
                )}
              </div>
            )}

            {activeTab === 'weather' && (
              <div className="space-y-2">
                <button
                  onClick={() => setFormData({ ...formData, weather_approved: !formData.weather_approved })}
                  className={cn(
                    'w-full rounded-lg border px-4 py-3 text-left font-semibold transition-all',
                    formData.weather_approved ? 'bg-green-500/10 border-green-500/30 text-green-400' : 'bg-orange-500/10 border-orange-500/30 text-orange-400'
                  )}
                >
                  {formData.weather_approved ? '✓ Weather Approved' : '○ Weather - Needs Review'}
                </button>
                <p className="text-xs text-muted-foreground">METAR/TAF/SIGMET review required</p>
              </div>
            )}

            {activeTab === 'performance' && (
              <div className="space-y-2">
                <button
                  onClick={() => setFormData({ ...formData, performance_approved: !formData.performance_approved })}
                  className={cn(
                    'w-full rounded-lg border px-4 py-3 text-left font-semibold transition-all',
                    formData.performance_approved ? 'bg-green-500/10 border-green-500/30 text-green-400' : 'bg-orange-500/10 border-orange-500/30 text-orange-400'
                  )}
                >
                  {formData.performance_approved ? '✓ Performance Approved' : '○ Performance - Needs Review'}
                </button>
                <p className="text-xs text-muted-foreground">Takeoff/landing distance confirmed</p>
              </div>
            )}

            {activeTab === 'crew' && (
              <div className="space-y-2">
                <button
                  onClick={() => setFormData({ ...formData, crew_approved: !formData.crew_approved })}
                  className={cn(
                    'w-full rounded-lg border px-4 py-3 text-left font-semibold transition-all',
                    formData.crew_approved ? 'bg-green-500/10 border-green-500/30 text-green-400' : 'bg-orange-500/10 border-orange-500/30 text-orange-400'
                  )}
                >
                  {formData.crew_approved ? '✓ Crew Legal' : '○ Crew - Needs Review'}
                </button>
                <p className="text-xs text-muted-foreground">FAR 117 compliance verified</p>
              </div>
            )}

            {activeTab === 'review' && (
              <div className="space-y-2">
                <button
                  onClick={() => setFormData({ ...formData, mel_approved: !formData.mel_approved })}
                  className={cn(
                    'w-full rounded-lg border px-4 py-3 text-left font-semibold transition-all',
                    formData.mel_approved ? 'bg-green-500/10 border-green-500/30 text-green-400' : 'bg-orange-500/10 border-orange-500/30 text-orange-400'
                  )}
                >
                  {formData.mel_approved ? '✓ MEL/CDL Approved' : '○ MEL/CDL - Needs Review'}
                </button>
              </div>
            )}
          </div>

          {/* Action buttons */}
          <div className="flex gap-2">
            <button
              onClick={handleSubmit}
              disabled={!allComplete || createMutation.isPending}
              className={cn(
                'flex-1 h-10 rounded-lg font-bold text-sm transition-all focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1',
                allComplete ? 'bg-primary text-primary-foreground hover:bg-primary/90' : 'bg-secondary text-muted-foreground cursor-not-allowed'
              )}
            >
              {createMutation.isPending ? 'Creating Release…' : 'Create & Sign Release'}
            </button>
            {existingRelease && (
              <button className="h-10 px-4 rounded-lg border border-border text-foreground font-bold text-sm hover:bg-secondary transition-colors focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1">
                Amend Release
              </button>
            )}
          </div>
        </>
      )}
    </div>
  );
}